### ISSUE TITLE
Update Explorer packages and solve breaking changes

### ISSUE THREAD

**Issue by damienen** [Itheum/explorer-dapp#302]
There are some packages that have breaking changes that need to be addressed on Explorer:
@radix-ui/react-dialog
react-inlinesvg

**Comment by Enciusan** [comment]
After some research i see that there are some changes if you update @types/react lib and also you have to upgrade typescript in order to fix the error regarding error 
'SVG' cannot be used as a JSX component.
  Its return type 'string | number | boolean | Element | Iterable<ReactNode> | null | undefined' is not a valid JSX element.

Reference:
https://github.com/gilbarbara/react-inlinesvg/issues/217
https://github.com/facebook/react/issues/24304
https://github.com/software-mansion/react-native-svg/issues/1741

**Comment by damienen** [comment]
Solved. Closing
